language: cpp

compiler:
- clang
- gcc

os:
- linux
- osx

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
    - mkdir BUILD && cd BUILD && mkdir debug && cd debug && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ../.. && cmake --build .

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
