language: cpp

compiler:
- clang
- gcc

os:
- linux
- osx

script: mkdir BUILD && cd BUILD && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target coveralls
